/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package views;

import java.awt.Color;
import java.awt.Font;
import repository.MsgBox;
import repository.RandomSNN;
import service.QuenMatKhauService;

/**
 *
 * @author hoanh
 */
public class QuenMKJdialog extends javax.swing.JDialog {

    /** Creates new form QuenMKJdialog */
    public QuenMKJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        maCP();
        GoiY();
        setLocationRelativeTo(null);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCapCha = new javax.swing.JTextField();
        btnResest = new javax.swing.JButton();
        lblCapCha = new javax.swing.JLabel();
        btnGui = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSwing/forgot (1).png"))); // NOI18N
        jLabel1.setText("     ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Quên mật khẩu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 44, -1, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 94, 360, -1));

        txtCapCha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Capcha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        txtCapCha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCapChaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCapChaFocusLost(evt);
            }
        });
        txtCapCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapChaActionPerformed(evt);
            }
        });
        jPanel2.add(txtCapCha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 215, 60));

        btnResest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSwing/Everaldo-Kids-Icons-Reload.16.png"))); // NOI18N
        btnResest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResestActionPerformed(evt);
            }
        });
        jPanel2.add(btnResest, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 190, 31, 33));

        lblCapCha.setText("-");
        jPanel2.add(lblCapCha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 84, 32));

        btnGui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSwing/Benzlee-Free-Christmas-Paper-airplane.24.png"))); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });
        jPanel2.add(btnGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 269, -1, -1));

        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSwing/Hopstarter-Sleek-Xp-Basic-Close-2.16.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 269, -1, 31));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 0, 420, 342));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResestActionPerformed
        // TODO add your handling code here:
        maCP();
    }//GEN-LAST:event_btnResestActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
guiEmail();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCapChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapChaActionPerformed
        // TODO add your handling code here:
        if(txtEmail.getText().equalsIgnoreCase("")){
            txtEmail.setText("email...");
            txtEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCapChaActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
         if(txtEmail.getText().equalsIgnoreCase("email...")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().equalsIgnoreCase("email...")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtCapChaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapChaFocusGained
        // TODO add your handling code here:
        if(txtCapCha.getText().equalsIgnoreCase("capcha...")){
            txtCapCha.setText("");
            txtCapCha.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCapChaFocusGained

    private void txtCapChaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapChaFocusLost
        // TODO add your handling code here:
        if(txtCapCha.getText().equalsIgnoreCase("")){
            txtCapCha.setText("capcha...");
            txtCapCha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCapChaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMKJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMKJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMKJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMKJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMKJdialog dialog = new QuenMKJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnResest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCapCha;
    private javax.swing.JTextField txtCapCha;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

    void GoiY(){
        txtEmail.setText("email...");
        txtEmail.setForeground(Color.gray);
        txtCapCha.setText("capcha...");
        txtCapCha.setForeground(Color.gray);
        txtCapCha.requestFocus();
    }
    void maCP() {
        String capcha = new RandomSNN().soNgauNhienString(5);
        lblCapCha.setText(capcha);
        lblCapCha.setFont(new Font(capcha, Font.HANGING_BASELINE, 14));
    }
    
    void LamMoi(){
        GoiY();
        maCP();
    }
    
    
    boolean ktloi() {
        if(txtEmail.getText().equalsIgnoreCase("email...")){
            txtEmail.requestFocus();
            MsgBox.alert(this, "Không được để Email trống");
            return false;
        }
        if(txtCapCha.getText().equalsIgnoreCase("capcha...")){
            txtCapCha.requestFocus();
            MsgBox.alert(this, "Không được để Capcha trống");
            return false;
        }
        
        if(txtEmail.getText().trim().equalsIgnoreCase("")){
            txtEmail.requestFocus();
            MsgBox.alert(this, "Không được để Email trống");
            return false;
        }
        if(txtCapCha.getText().trim().equalsIgnoreCase("")){
            txtCapCha.requestFocus();
            MsgBox.alert(this, "Không được để Capcha trống");
            return false;
        }
        if(!txtCapCha.getText().equalsIgnoreCase(lblCapCha.getText())){
            txtCapCha.requestFocus();
            MsgBox.alert(this, "Mã Capcha Không Khớp");
            maCP();
            return false;
        }
        return true;
    }
    QuenMatKhauService qmkService = new QuenMatKhauService();
    void guiEmail() {
        if (ktloi()) {
            try {
                if (qmkService.checkuser(txtEmail.getText())) {
                    qmkService.updateMK(txtEmail.getText());
                    LamMoi();
                    return;
                }
                MsgBox.alert(this, "Gửi yêu câu thất bại không có Email trên");
                LamMoi();
                return;
            } catch (Exception e) {
                //e.printStackTrace();
            }
        }
    }
}
